id: P4AC1A4CC
initial_creation_type: ocr
source_metadata:
  volumes:
    ad9996e4a99e4ba9bcb08940d1460ee6:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
